console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
    foreground_templates = [
        "{{if gt .Code 0}}p:bright_red{{end}}",
    ]
    foreground = "p:green"
    background = "transparent"
    template = " "

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

    [[blocks.segments]]
        type = "text"
        style = "plain"
        background = "transparent"
        foreground_templates = [
            "{{if gt .Code 0}}p:bright_red{{end}}",
        ]
        foreground = "p:green"
        template = "┌ "

    [[blocks.segments]]
        type = "path"
        style = "plain"
        background = "transparent"
        foreground = "p:blue"
        template = '{{ .Path }}'

        [blocks.segments.properties]
        style = "agnoster_full"
        home_icon = "󱂵" 
    [[blocks.segments]]
        type = "status"
        style = "diamond"
        foreground = "p:blue"
        foreground_templates = ["{{ if gt .Code 0}}p:red{{end}}"]

[[blocks]]
    type = "prompt"
    alignment = "right"

    [[blocks.segments]]
        type = "executiontime"
        style = "plain"
        foreground = "p:blue"
        [blocks.segments.properties]
            always_enabled = true
    [[blocks.segments]]
        type = "os"
        foreground = "#1793D1"
    [[blocks.segments]]
        type = "git"
        style = "plain"
        foreground = "p:blue"
        fetch_status = true
        fetch_upstream_icon = true
        branch_icon = "\uE5FB"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true
    [[blocks.segments]]
        type = "text"
        style = "plain"
        foreground_templates = [
            "{{if gt .Code 0}}p:bright_red{{end}}",
        ]
        foreground = "p:green"
        background = "transparent"
        template = "└─►"






[palette]
background = "#24283b"
foreground = "#a9b1d6"
cursor = "#c0caf5"

black = "#1a1b26"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

bright_black = "#565f89"
bright_red = "#ff7a93"
bright_green = "#b9f27c"
bright_yellow = "#ff9e64"
bright_blue = "#7aa2f7"
bright_magenta = "#bb9af7"
bright_cyan = "#7dcfff"
bright_white = "#c0caf5"
